import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Topbar from "./topbar";
import Navbar from "./navbar";
import Footer from "./footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Fixed Topbar and Navbar */}
        <div className="fixed top-0 left-0 w-full z-20">
          <Topbar />
          <Navbar />
        </div>

        {/* Main Content */}
        <main className="flex-grow ">
          {/* Adjust the top margin based on the combined height of Topbar and Navbar */}
          {children}
        </main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
